services:
  hwaroak-api:
    image: ghcr.io/${ORG_NAME}/hwaroak-api:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - my-network

  redis:
    image: redis:7.4.1
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - my-network

  nginx:
    image: nginx:1.27.4
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork
    restart: always

volumes:
  redis_data:

networks:
  my-network:
    driver: bridge