spring:
  application:
    name: hwarok

  profiles:
    group:
      local: "local"
      dev: "dev"

  #jpa
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  # kakao access, refresh token

  data:
    redis:
      host: localhost
      port: 6379
      # 필요 시 password도 설정할 수 있습니다.
      # password: your_redis_password
jwt:
  secret : my-super-secure-secret-key-123456  # ✅ 최소 32자 이상
  access-token-validity : 3600      # 1시간
  refresh-token-validity : 1209600  # 14일