spring:
  application:
    name: hwarok

  profiles:
    group:
      local: "local"
      dev: "dev"

  #jpa
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  # kakao access, refresh token

  data:
    redis:
      host: localhost
      port: 6379
      # password: your_redis_password
jwt:
  secret : ${JWT_SECRET} #my-super-secure-secret-key-123456
  access-token-validity : 3600000           # 1시간
  refresh-token-validity : 2592000000       # 30일


