spring:
  config:
    activate:
      on-profile: "dev"
    import: optional:env[.env]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: gpt-3.5-turbo

  data:
    redis:
      host: ${REDIS_DEV_HOST}
      port: 6379

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: hwaroak-user-profile-bucket


jwt:
  secret : ${JWT_SECRET}
  access-token-validity : 2592000000           # 1일 = 24 * 60 * 60 * 1000
  refresh-token-validity : 2592000000       # 30일


app:
  s3:
    region: ap-northeast-2
    bucket: hwaroak-user-profile-bucket
    key-prefix: profiles             # 프로필 이미지 경로 prefix
    presign-ttl-seconds: 600         # Presigned URL 유효 시간 (초)
    allowed-content-types: image/jpeg,image/png,image/webp